### ISSUE TITLE
Various errors and warnings

### ISSUE THREAD

**Issue by eldoy** [eldoy/skilt#5]
```
Route for localhost not found.
Route for localhost not found.
Route for localhost not found.
/Users/vidar/.nvm/versions/node/v16.15.1/lib/node_modules/skilt/node_modules/rekvest/index.js:13
  req.href = decodeURI(req.href)
             ^

URIError: URI malformed
    at decodeURI (<anonymous>)
    at module.exports (/Users/vidar/.nvm/versions/node/v16.15.1/lib/node_modules/skilt/node_modules/rekvest/index.js:13:14)
    at getRoute (/Users/vidar/.nvm/versions/node/v16.15.1/lib/node_modules/skilt/index.js:55:3)
    at Server.<anonymous> (/Users/vidar/.nvm/versions/node/v16.15.1/lib/node_modules/skilt/index.js:67:17)
    at Server.emit (node:events:527:28)
    at parserOnIncoming (node:_http_server:956:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
```

**Comment by eldoy** [comment]
Seems to crash on this:

```
http://tracker.trackerfix.com/scrape?info_hash=%87h%ce%e8%e0%86%7f%b9%d3%10%ed%f1%40%a4q%f6%a1k%83%bf
```

**Comment by eldoy** [comment]
Guess we can just drop bad urls?
